#!/usr/bin/env bash
set -Eeuo pipefail

# --- CONFIG ---
BENCH_ROOT="${BENCH_ROOT:-$HOME/frappe-bench}"
ASSETS_ROOT="${ASSETS_ROOT:-$BENCH_ROOT/sites/assets/ifitwala_doc}"
OUT_CONF="${OUT_CONF:-/etc/nginx/conf.d/ifitwala_doc_static.inc}"

echo "==> Installing Ifitwala Doc nginx configuration"
echo "   BENCH_ROOT  : $BENCH_ROOT"
echo "   ASSETS_ROOT : $ASSETS_ROOT"
echo "   Output file : $OUT_CONF"
echo

# --- VALIDATE ENV ---
if [[ ! -d "$ASSETS_ROOT" ]]; then
  echo "❌ ERROR: Assets directory not found: $ASSETS_ROOT" >&2
  echo "Run deploy_docs.sh first or check BENCH_ROOT / ASSETS_ROOT."
  exit 1
fi

# --- WRITE NGINX CONFIG DIRECTLY ---
sudo tee "$OUT_CONF" >/dev/null <<NGINX
# ==============================================================
# Ifitwala Docs & Marketing Static Pages
# Auto-generated by install_ifitwala_nginx.sh
# ==============================================================

# ---- Astro built assets (immutable) ----
location /docs/_astro/ {
    alias ${ASSETS_ROOT}/_astro/;
    try_files \$uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
}

# ---- Static documentation pages ----
location /docs/ {
    alias ${ASSETS_ROOT}/docs/;
    index index.html;
    try_files \$uri \$uri/index.html \$uri/ /docs/index.html;
}

# ---- Static marketing 'features' pages ----
location ^~ /features/ {
    alias ${ASSETS_ROOT}/features/;
    index index.html;
    try_files \$uri \$uri/ =404;
}

# ---- Root-level marketing pages generated by Astro ----
location ~ ^/(book-a-call|book-a-demo|pricing|about|services|data-governance|education|ifitwala-ed|platform|implementation|security|insights)(/|$) {
    root ${ASSETS_ROOT};
    try_files \$uri \$uri/index.html \$uri/ =404;
}
NGINX

# --- TEST & RELOAD ---
echo
echo "==> Testing nginx configuration"
sudo nginx -t

echo "==> Reloading nginx service"
sudo systemctl reload nginx

echo
echo "✅ Nginx static routes file created at: $OUT_CONF"
echo
echo "⚠️  IMPORTANT STEP REQUIRED ⚠️"
echo "To enable these routes, you must EDIT your main Nginx configuration"
echo "(usually /etc/nginx/conf.d/frappe-bench.conf) and add this line"
echo "inside the 'server {' block for your site:"
echo
echo "    include $OUT_CONF;"
echo
echo "Then reload nginx: sudo service nginx reload"
