#!/usr/bin/env node
/**
 * Synchronise theme tokens from Frappe (Ifitwala Theme Settings) into src/styles/tokens.css.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const targetPath = path.join(projectRoot, 'src', 'styles', 'tokens.css');

const DEFAULT_THEME = {
  ink_color: '#0F172A',
  slate_color: '#475569',
  canopy_color: '#12563A',
  leaf_color: '#2F855A',
  moss_color: '#A6D6B1',
  sky_color: '#E6F3F9',
  sand_color: '#F4EFE7',
  border_color: '#E2E8F0',
  radius_lg: '1rem',
  radius_xl: '1.25rem',
  shadow_soft: '0 6px 20px rgba(15, 23, 42, 0.06)',
  shadow_strong: '0 12px 32px rgba(15, 23, 42, 0.1)',
  focus_ring: '0 0 0 3px rgba(47, 133, 90, 0.35)',
};

const THEME_ORDER = [
  'ink_color',
  'slate_color',
  'canopy_color',
  'leaf_color',
  'moss_color',
  'sky_color',
  'sand_color',
  'border_color',
  'radius_lg',
  'radius_xl',
  'shadow_soft',
  'shadow_strong',
  'focus_ring',
];

const argFlags = new Set(process.argv.slice(2));
const silent = argFlags.has('--silent');

function resolveBase() {
  const candidates = [
    process.env.PUBLIC_SITE_API,
    process.env.SITE_API_BASE,
    process.env.PUBLIC_DOCS_API,
    process.env.DOCS_API_BASE,
    'http://127.0.0.1:8000',
  ];
  for (const item of candidates) {
    if (item && typeof item === 'string' && item.trim().length) {
      return item.trim();
    }
  }
  return 'http://127.0.0.1:8000';
}

async function fetchTheme() {
  const base = resolveBase();
  const url = new URL('/api/method/ifitwala_doc.api.site.get_theme', base).toString();
  const headers = {
    'User-Agent': 'ifitwala-doc/theme-sync',
    Accept: 'application/json',
  };
  try {
    const res = await fetch(url, { headers });
    if (!res.ok) {
      throw new Error(`${res.status} ${res.statusText}`);
    }
    const json = await res.json();
    return (json && typeof json === 'object' && 'message' in json) ? json.message : json;
  } catch (error) {
    if (!silent) {
      console.warn('[theme] Falling back to defaults:', error?.message || error);
    }
    return { ...DEFAULT_THEME };
  }
}

function normaliseTheme(theme) {
  const output = { ...DEFAULT_THEME };
  if (theme && typeof theme === 'object') {
    for (const key of THEME_ORDER) {
      const value = theme[key];
      if (typeof value === 'string' && value.trim().length) {
        output[key] = value.trim();
      }
    }
  }
  return output;
}

function hexToRgbString(value) {
  if (!value || typeof value !== 'string') {
    return null;
  }
  const hex = value.replace('#', '').trim();
  if (![3, 6].includes(hex.length)) {
    return null;
  }
  const segments = hex.length === 3
    ? hex.split('').map((ch) => parseInt(ch + ch, 16))
    : [hex.slice(0, 2), hex.slice(2, 4), hex.slice(4, 6)].map((part) => parseInt(part, 16));
  if (segments.some((num) => Number.isNaN(num))) {
    return null;
  }
  return segments.join(' ');
}

function buildCss(theme) {
  const lines = [
    '/* Auto-generated by scripts/pull_theme_tokens.mjs */',
    ':root {',
    '  /* Core palette */',
    `  --ink: ${theme.ink_color};`,
    `  --slate: ${theme.slate_color};`,
    `  --canopy: ${theme.canopy_color};`,
    `  --leaf: ${theme.leaf_color};`,
    `  --moss: ${theme.moss_color};`,
    `  --sky: ${theme.sky_color};`,
    `  --sand: ${theme.sand_color};`,
    `  --border: ${theme.border_color};`,
    `  --ink-rgb: ${hexToRgbString(theme.ink_color) || '15 23 42'};`,
    `  --slate-rgb: ${hexToRgbString(theme.slate_color) || '71 85 105'};`,
    `  --canopy-rgb: ${hexToRgbString(theme.canopy_color) || '18 86 58'};`,
    `  --leaf-rgb: ${hexToRgbString(theme.leaf_color) || '47 133 90'};`,
    `  --moss-rgb: ${hexToRgbString(theme.moss_color) || '166 214 177'};`,
    `  --sky-rgb: ${hexToRgbString(theme.sky_color) || '230 243 249'};`,
    `  --sand-rgb: ${hexToRgbString(theme.sand_color) || '244 239 231'};`,
    `  --border-rgb: ${hexToRgbString(theme.border_color) || '226 232 240'};`,
    '',
    '  /* Radii & shadows */',
    `  --radius-lg: ${theme.radius_lg};`,
    `  --radius-xl: ${theme.radius_xl};`,
    `  --shadow-soft: ${theme.shadow_soft};`,
    `  --shadow-strong: ${theme.shadow_strong};`,
    `  --focus: ${theme.focus_ring};`,
    '}',
    '',
  ];
  return lines.join('\n');
}

async function main() {
  const theme = normaliseTheme(await fetchTheme());
  const css = buildCss(theme);
  fs.writeFileSync(targetPath, css, 'utf8');
  if (!silent) {
    console.log(`[theme] Wrote tokens to ${path.relative(projectRoot, targetPath)}`);
  }
}

main().catch((error) => {
  console.error('[theme] Failed to write tokens:', error);
  process.exitCode = 1;
});
