// scripts/pull_theme_tokens.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const targetPath = path.join(projectRoot, 'src', 'styles', 'tokens.css');

const DEFAULT_THEME = {
  ink_color: '#0F172A',
  slate_color: '#475569',
  canopy_color: '#12563A',
  leaf_color: '#2F855A',
  moss_color: '#A6D6B1',
  sky_color: '#E6F3F9',
  sand_color: '#F4EFE7',
  border_color: '#E2E8F0',
  radius_lg: '1rem',
  radius_xl: '1.25rem',
  shadow_soft: '0 6px 20px rgba(15, 23, 42, 0.06)',
  shadow_strong: '0 12px 32px rgba(15, 23, 42, 0.1)',
  focus_ring: '0 0 0 3px rgba(47, 133, 90, 0.35)',
};

const THEME_ORDER = [
  'ink_color', 'slate_color', 'canopy_color', 'leaf_color',
  'moss_color', 'sky_color', 'sand_color', 'border_color',
  'radius_lg', 'radius_xl', 'shadow_soft', 'shadow_strong', 'focus_ring',
];

const argFlags = new Set(process.argv.slice(2));
const silent = argFlags.has('--silent');

function resolveBase() {
  return process.env.PUBLIC_SITE_API || process.env.SITE_API_BASE || 'http://127.0.0.1:8000';
}

async function fetchTheme() {
  const base = resolveBase();
  const url = new URL('/api/method/ifitwala_doc.api.site.get_theme', base).toString();
  try {
    const res = await fetch(url, { headers: { Accept: 'application/json' } });
    if (!res.ok) throw new Error(`${res.status}`);
    const json = await res.json();
    return json.message || json;
  } catch (error) {
    if (!silent) console.warn('[theme] Falling back to defaults');
    return { ...DEFAULT_THEME };
  }
}

function hexToRgbString(value) {
  const hex = value.replace('#', '').trim();
  const segments = hex.length === 3
    ? hex.split('').map((ch) => parseInt(ch + ch, 16))
    : [hex.slice(0, 2), hex.slice(2, 4), hex.slice(4, 6)].map((part) => parseInt(part, 16));
  return segments.join(' ');
}

function buildCss(theme) {
  return `/* Auto-generated by scripts/pull_theme_tokens.mjs */
:root {
  /* Legacy compatibility variables */
  --ink: ${theme.ink_color};
  --slate: ${theme.slate_color};
  --canopy: ${theme.canopy_color};
  --leaf: ${theme.leaf_color};
  --moss: ${theme.moss_color};
  --sky: ${theme.sky_color};
  --sand: ${theme.sand_color};
  --border: ${theme.border_color};
  --ink-rgb: ${hexToRgbString(theme.ink_color)};
  --slate-rgb: ${hexToRgbString(theme.slate_color)};
  --canopy-rgb: ${hexToRgbString(theme.canopy_color)};
  --leaf-rgb: ${hexToRgbString(theme.leaf_color)};
  --moss-rgb: ${hexToRgbString(theme.moss_color)};
  --sky-rgb: ${hexToRgbString(theme.sky_color)};
  --sand-rgb: ${hexToRgbString(theme.sand_color)};
  --border-rgb: ${hexToRgbString(theme.border_color)};
  
  /* Additional tokens mapped to CSS vars */
  --radius-lg: ${theme.radius_lg};
  --radius-xl: ${theme.radius_xl};
  --shadow-soft: ${theme.shadow_soft};
  --shadow-strong: ${theme.shadow_strong};
}
`;
}

async function main() {
  const data = await fetchTheme();
  const theme = { ...DEFAULT_THEME };
  for (const key of THEME_ORDER) {
    if (data[key]) theme[key] = data[key];
  }
  fs.writeFileSync(targetPath, buildCss(theme), 'utf8');
}

main().catch(() => process.exit(1));